.gitignore, factory/Dockerfile
All works locally, not sure what specific version of maven would be better so kept it more general. Also removed dockerfile from gitignore for obvious reasons.
=> Factory dockerfile

azure-pipeline.yml
There doesn't seem to be any tests for npm, needs to be verified, but this should serve as a good starting point.
=> Solid initial pipeline, need to verify tests

terraform/.gitignore, terraform/backend/backend.tf, terraform/backend/variables.tf
This will allow us to managed terraform.tfstate across machines.
=> created backend storage account container for terraform fstate management

kubernetes/order-deployment.yml, kubernetes/order-service.yml
Kubernetes files for order service + deployment. Image name may need amending based on pipeline naming scheme and secretref will be made and attatched once the database is up.
=> order kubernetes

azure-pipeline.yml
Now the pipeline will be able to push all images appropriately, once they are completed and the pipeline re-enabled.
=> added order service deployment to pipeline

kubernetes/order-deployment.yml, kubernetes/order-hpa.yml
hpa order service yml completed. Additional resource block added to the order service deployment. Numbers selected in cpu etc. can be placeholders and changed if they aren't high enough/too low.
=> Hpa order service

kubernetes/wedding-watches-deployment.yml, kubernetes/wedding-watches-service.yml
kubernetes yml for wedding watches and service + deployment
=> Wedding watches kubernetes

terraform/main/init_backend.sh, terraform/main/main.tf, terraform/main/variables.tf
Also accompanied by bash script for terraform init. Both bash script and terraform files dynamically account for terraform workspace in order to faciliate both dev and prod resources.
=> Created resources for dev postgres server and database

terraform/backend/container-registry.tf, terraform/backend/variables.tf
This will isolate the repositories for our project from ones for other projects.
=> Created new container registry as part of backend

kubernetes/order-deployment.yml
works fully with service connector in azure. image name changed until we get permissions working for the cluster!
=> secret added

wedding-watches/Dockerfile
=> Add wedding watches dockerfile

kubernetes/workflow-dep.yml
This also matches up with the azure pipeline now.
=> small amendment to workflow-dep.yml for consistency

factory/Dockerfile
It separates things out into two stages and transfers the created file from maven correctly.
=> Fixed factory dockerfile to work within the azure pipeline

kubernetes/wedding-watches-deployment.yml, kubernetes/wedding-watches-hpa.yml
Hpa for wedding watches yml file added. Amended the original deployment yaml with resource limits/requests so the hpa will work. Values used in the hpa can be changed once we get a better understanding of cpu usage and potentially memory usage.
=> wedding watches hpa

terraform/backend/backend.tf, terraform/backend/devops.tf, terraform/backend/variables.tf
Creating the actual service connection seems problematic with unclear documentation, so commented out those parts for now.
=> created managed identity to use in devops service connection

terraform/backend/kubernetes-cluster.tf
I'm lacking permissions to apply those resources at the moment so I'll comment them out so I can still terraform apply successfully.
=> temporarily commented out role assignemnts for kubernetes cluster 

terraform-pipeline-dev.yml, terraform/main/main.tf
This automatically applies changes to terraform resources, with the exception being if they would destroy either database (in which case something has gone very wrong).
=> created terraform dev pipeline

kubernetes/README.md
Readme for deploying the kubernetes services. Let me know if anything is missing/inconsistent!
=> kubernetes readme

kubernetes/order-deployment.yml
Changed name of order service secret to be consistent.
=> secret name change

terraform-pipeline-dev.yml
Now each step explicity switches to the "dev" workspace.
=> fix to terraform pipeline reverting to default workspace

factory/pom.xml, factory/src/main/java/com/folex/factory/controller/OrderController.java, factory/src/main/java/com/folex/factory/model/FactoryOrder.java, factory/src/main/java/com/folex/factory/store/InmemoryFactoryOrderStore.java, kubernetes/README.md, order-service/pom.xml, order-service/src/main/java/com/folex/orderservice/controller/OrderController.java, order-service/src/main/java/com/folex/orderservice/model/WatchOrder.java, wedding-watches/src/app.html, workflow/Dockerfile, workflow/src/main/resources/process/watch_order.bpmn
Order service was fixed by Andrew
=> Update order service

workflow/src/main/java/com/folex/workflow/configuration/RabbitConfiguration.java
=> fix rabbit configuration

queries.kql
Queries to be used in the azure logs to create an azure dashboard (since we can't save logs on azure).
=> kql queries

azure-pipeline.yml
My bad on this one guys (that's what reviewing is for, if I'm an idiot you guys need to let me know).
=> Fixed accidentally deploying factory docker image to order service repo

azure-pipeline.yml
Hopefully this should work, even if I can't currently get Helm working.
=> Auto update service images

terraform/README.md
Some explanation regarding the logic of the terraform files, how to set up tfvars/.env files, and how to init and run everything.
=> simple readme for terraform section
